### PR TITLE
Create CNAME

### PR DESCRIPTION
**Pull request by renefritze**
allows accessing the site via spring1944.net (once DNS changes are done)

### CODE REVIEW

**Comment by specing** [comment]
Hi there! Who wields the power to make DNS changes?

**Comment by renefritze** [comment]
I still think that's @tvo, but I'm neither sure nor do I know if anybody hab contacted him at some point. I also don't even know who's still around working on S44 these days. I'm waaaayy out of touch. I wouldn't mind not hosting the site somewhen, also.

**Comment by tvo** [comment]
I'm way out of touch too but I do still control the domain, so I can
probably create a CNAME. What is the CNAME you want me to create?

**Comment by specing** [comment]
For now spring1944.github.io. We would certainly like to preserve the old stuff even though it might not be publicly accessible (and it shouldn't be, given the bit rot). There is a new forum at discuss.s44.eu for which Frju would need a database dump of the old forum to migrate posts & co (or for someone to modernise the old forum). Useful parts of the old website would eventually be moved to the new one.

Was there at one point in time a seperate website on spring1944 dot com? I seem to remember something like that.

**Comment by tvo** [comment]
I've updated spring1944.net to point to spring1944.github.io. TTL is 1 day though so give it a bit to propagate. I also have spring1944.eu and spring1944.org; I've kept those pointing at the old website (I believe they were never really popularized -- for now they might be a convenient way to keep accessing the old content).

Apart from the domain I've never controlled/hosted any S44 web content, so I don't have access to the database.

Great to see some things going on here BTW :)

**Comment by renefritze** [comment]
DB access would be me. I can certainly send, privately + encrypted if possible, a db dump somewhere. 

OTOH, can't you do that through the board software?

**Comment by frju365** [comment]
I would like to have the db of the old forum to set up completely the new forum : discuss.s44.eu if it's possible. 
I'm admin on the old forum and my email adress is the github one : abld@tutanota.com (You can send me a mail)

**Comment by specing** [comment]
Ok, now spring1944.github.io redirects to the old website... While spring1944.net is still the old one.

**Comment by specing** [comment]
Pages documentation mentions no CNAMEs that would have to be set in the repository itself, but it does mention a settings button that I cannot see/access:
https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/
https://help.github.com/articles/setting-up-an-apex-domain/

**Comment by renefritze** [comment]
So if someone already made you admin, why not use the board backup functionality, @frju365 ?
https://www.phpbb.com/support/docs/en/3.1/ug/adminguide/maintenance_database/

**Comment by frju365** [comment]
In ACP Board < Maintenance, I see only Admin logs on the right... but no bakcup/restore feature...

**Comment by specing** [comment]
@tvo spring1944.net and the other two still point to the same address.

**Comment by tvo** [comment]
Hmm I did change it in the DNS admin dashboard. However, I just did some digging and realized that it's actually not possible to CNAME a root domain to another URL: 

https://serverfault.com/questions/613829/why-cant-a-cname-record-be-used-at-the-apex-aka-root-of-a-domain

I corrected it now by following the instructions @specing listed (thanks!). Created two A records for spring1944.net that point to the github IP addresses. Verified that the authoritative name server returned the correct IP addresses too. So give it a bit to propagate and then make sure that someone goes through the steps here: 

https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/

**Comment by frju365** [comment]
@renemilk : I'm admin but I've not founder status. So, I think it only works for admin with founder status.

**Comment by frju365** [comment]
In fact, if you could set @specing as admin of this repos it would be fine.

**Comment by tvo** [comment]
I don't think I'm admin? I'll check later, I'm traveling right now so can
only intermittently use my laptop...

**Comment by renefritze** [comment]
The DB is enormous. Mostly due to mediawiki. There's at least 3GB in those mw_ tables. A full gzipped export of the s44 DB is still ~370MB. Do you want everything, @frju365 ?

**Comment by specing** [comment]
gzip? What is this, 1990? xz it! Those 3GB are probably due to spammers. As I remember, Nemo was running a spam killer bot through the wiki itself, but I'm not sure whether any entries were actually deleted from the DB.

**Comment by frju365** [comment]
For me, only forum part of the db is enough. I don't need mediawiki or other things. 3GB is a bit too big. Moreover, first I will need to test it... I'm not sure nodebb software (mongodb in fact) will appreciate to convert every tables of phpBB.

**Comment by specing** [comment]
I can take the full 3GB no problem.

Someone with the required permissions would need to input "spring1944.net" under custom domain under repo settings for spring1944.net to finally work. Until that someone appears spring1944.net will be linked to my fork.

**Comment by ashdnazg** [comment]
@specing I have done that, it creates the CNAME file as you've seen

**Comment by ashdnazg** [comment]
Actually now I can't do that because the domain is "in use" I suspect it's because of your fork

**Comment by specing** [comment]
Interesting. Then why did manually setting CNAME not work? Anyway I've removed the domain now.

**Comment by renefritze** [comment]
You should've gotten a dropbox link, @frju365 
Will somebody please ping me if/when I can stop serving stuff from my box?

**Comment by frju365** [comment]
ok. I received it. Thanks. I will see if I can integrate it to mongodb.

**Comment by frju365** [comment]
Thank you very much, but after many critics of the spring1944 users about the forum, I decided to close it today definitely. In 3 months the forum will be removed and every sites associated (pads, URLshortener...). The s44.eu domain will stay as mine during one year after that(I bought it for 2 years), and will be available for sales after that.

And as @sanguinariojoe, @specing Code_Man and PepeAmpere are really happy I removed it, I decided that it was the moment to leave the Spring1944 community too.

Ofc: if you have any question or you want that I keep these other associated websites, tell me.

**Comment by specing** [comment]
I'm not really happy. In fact I'm not happy at all. I also don't know what made you think I could possibly be happy about it.

**Comment by sanguinariojoe** [comment]
@frju , too much drama man...

> but after many critics of the spring1944 users about the forum

I remember very little level of critics (provided some of the complainers acts like trolls). Anyway, you should expect a significant percentage of users complaining about your work in a small community. Such is life.

> And as @sanguinariojoe, @specing Code_Man and PepeAmpere are really happy I removed it, I decided that it was the moment to leave the Spring1944 community too.

As @specing, I'm not happy at all. Of course I wanna get your forum and you on board. But in such a case, the forum shall be stable enough to support a bit of trolling

**Comment by frju365** [comment]
In fact, as I said to @specing, it's nothing personal. I just find that a forum with 3 persons is not really useful. What PepeAmpere and Code_Man said is not "trolling", it's just the truth. The issue #93 of s44 proves it. Nobody wants to have a forum, even JAL and Buumi don't want to register to it. What is the point of having a forum where there is nobody ? In fact it's coming back to the old forum.

**Comment by frju365** [comment]
Moreover how many time I wasted to explain you what was the goal of the forum... I lost time with marioxcc, and I think it was enough clear. No need to explain it 20 hours more. I already gave all my energy. Sorry.

**Pull request merged**
