### PR TITLE
Github wiki links

### PR DESCRIPTION
**Pull request by sanguinariojoe**
Fixing the broken links to the gitlab wiki

### CODE REVIEW

**Comment by specing** [comment]
+1. Should we merge this or will you commit directly?
oh, and there were some other links I changed in the other commit that now need changing to github.

**Comment by frju365** [comment]
+1

**Comment by sanguinariojoe** [comment]
Merge please

P.S. When I make a PR, is because I actually want a formal merge process :-)

**Comment by specing** [comment]
ok, I thought it was just for review and I generally want to avoid unnecessary merge commits.

**Comment by specing** [comment]
I'm pretty sure something else still remains.

**Pull request merged**
